name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - master   

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          submodules: true  # Asegura que los submódulos (como temas) se descarguen

      - name: Instalar Hugo Extended
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Compilar sitio
        run: hugo --minify -s practica0/paginaEstatica --destination practica0/paginaEstatica/public
        env:
          HUGO_ENV: production  # Asegura un entorno de producción

      - name: Subir artefactos
        uses: actions/upload-pages-artifact@v3
        with:
          path: practica0/paginaEstatica/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4