name: Deploy site to GitHub Pages

on:
  push:
    branches:
      - main   # o la rama donde tienes tu código fuente

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Si usas Hugo, Jekyll, o Node, aquí va la compilación
      # Ejemplo con Hugo:
      - name: Instalar Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Compilar sitio
        run: hugo --minify

      - name: Subir artefactos
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./practica0/paginaEstatica  # carpeta donde queda el sitio generado

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
